### ISSUE TITLE
Multiple undocumented BC in DOM extension

### ISSUE THREAD

**Issue by WinterSilence** [php/doc-en#1205]
### Description

For example, many `DOMNamedNodeMap` methods was removed in PHP 8 without any information in "Breaking changes".
~~~php
$rc = new ReflectionClass(DOMNamedNodeMap::class);
echo (string) $rc;
~~~
[PHP 7.3](https://3v4l.org/fWo1m#v7.3.33)
```
Class [ <internal:dom> <iterateable> class DOMNamedNodeMap implements Traversable, Countable ] {
  - Methods [8] {
    Method [ <internal:dom> public method getNamedItem ] {
      - Parameters [1] {
        Parameter #0 [ <required> $name ]
      }
    }

    Method [ <internal:dom> public method setNamedItem ] {
      - Parameters [1] {
        Parameter #0 [ <required> DOMNode $arg ]
      }
    }

    Method [ <internal:dom> public method removeNamedItem ] {
      - Parameters [1] {
        Parameter #0 [ <optional> $name ]
      }
    }

    Method [ <internal:dom> public method item ] {
      - Parameters [1] {
        Parameter #0 [ <optional> $index ]
      }
    }

    Method [ <internal:dom> public method getNamedItemNS ] {
      - Parameters [2] {
        Parameter #0 [ <optional> $namespaceURI ]
        Parameter php/php-src#1 [ <optional> $localName ]
      }
    }

    Method [ <internal:dom> public method setNamedItemNS ] {
      - Parameters [1] {
        Parameter #0 [ <optional> DOMNode $arg ]
      }
    }

    Method [ <internal:dom> public method removeNamedItemNS ] {
      - Parameters [2] {
        Parameter #0 [ <optional> $namespaceURI ]
        Parameter php/php-src#1 [ <optional> $localName ]
      }
    }

    Method [ <internal:dom, prototype Countable> public method count ] {
      - Parameters [0] {
      }
    }
  }
}
```
[PHP 8.1](https://3v4l.org/fWo1m#v8.1.0)
```
Class [ <internal:dom> <iterateable> class DOMNamedNodeMap implements IteratorAggregate, Traversable, Countable ] {
  - Properties [1] {
    Property [ public int $length ]
  }

  - Methods [5] {
    Method [ <internal:dom> public method getNamedItem ] {
      - Parameters [1] {
        Parameter #0 [ <required> string $qualifiedName ]
      }
      - Tentative return [ ?DOMNode ]
    }

    Method [ <internal:dom> public method getNamedItemNS ] {
      - Parameters [2] {
        Parameter #0 [ <required> ?string $namespace ]
        Parameter php/php-src#1 [ <required> string $localName ]
      }
      - Tentative return [ ?DOMNode ]
    }

    Method [ <internal:dom> public method item ] {
      - Parameters [1] {
        Parameter #0 [ <required> int $index ]
      }
      - Tentative return [ ?DOMNode ]
    }

    Method [ <internal:dom, prototype Countable> public method count ] {
      - Parameters [0] {
      }
      - Tentative return [ int ]
    }

    Method [ <internal:dom, prototype IteratorAggregate> public method getIterator ] {
      - Parameters [0] {
      }
      - Return [ Iterator ]
    }
  }
}
```
Other DOM classes haves same BC.

### PHP Version

7.1 - 8.1

### Operating System

no matter

**Comment by WinterSilence** [comment]
@cmb69  **No matter, implemented or not - that's methods defined in code**. For example: I'm create ` class NamedNodeMap extends  DOMNamedNodeMap implements IteratorAggregate` in PHP7
- I'm can't define method `NamedNodeMap::removeNamedItem(string $name)` because method already defined as `DOMNamedNodeMap::removeNamedItem($name = null)` in PHP7
- I'm implement method `IteratorAggregate::getIterator()` as `NamedNodeMap:getIterator(): Generator` in PHP7, but that's method generate error in PHP8

**Parameters of implemented methods have changed too**. For example,
in PHP7:
```
Method [ <internal:dom> public method item ] {
    - Parameters [1] {
      Parameter #0 [ <optional> $index ]
    }
 }
```
in PHP8:
```
Method [ <internal:dom> public method item ] {
  - Parameters [1] {
    Parameter #0 [ <required> int $index ]
  }
  - Tentative return [ ?DOMNode ]
}
```
i.e. any class extending `DOMNamedNodeMap` and overriding implemented methods and writing on PHP7 don't works in PHP8.

P.S. Closing issues without discus it's bad practice.

**Comment by cmb69** [comment]
Well, you have obviously filed that as documentation issue; the title is "Multiple undocumented BC in DOM extension", and you started by claiming "For example, many DOMNamedNodeMap methods was removed in PHP 8 without any information in "Breaking changes"." The documentation has been updated accordingly, so case closed. :)

> i.e. any class extending DOMNamedNodeMap and overriding implemented methods and writing on PHP7 after update to PHP8 generates fatal errors.

It is highly unlikely that the BC break of these changes has not been considered at all; it looks more like an overdue cleanup, for which a new *major* versions appears to be suitable. If you want php-src to revert that change (which happened more than a year ago), please write to the [internals mailing list](https://www.php.net/mailing-lists.php#internals).

**Comment by WinterSilence** [comment]
_Undocumened_ - I'm mean that's not declared in manual in [Backward Incompatible Changes](https://www.php.net/manual/en/migration81.incompatible)

**Comment by cmb69** [comment]
It is now in the [Backward Incompatible Changes chapter of the PHP 7.4 to PHP 8.0 migration guide](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.dom).

**Comment by WinterSilence** [comment]
@ cmb69
> If you want php-src to revert that change (which happened more than a year ago), please write to the internals mailing list.

why I'm can't do it here? "internals mailing list" is "technology of dark ages" (:

stop, stop.. not so fast.. what's about second part?
> **Parameters of implemented methods have changed too**

**Comment by Girgias** [comment]
> > If you want php-src to revert that change (which happened more than a year ago), please write to the internals mailing list.
> 
> why I'm can't do it here? "internals mailing list" is "technology of dark ages" (:

This is the document tracker, not the place where we talk about language changes.

**Comment by kamil-tekiela** [comment]
PHP is maintained by volunteers just like you and me. The process for requesting changes starts with emailing other people. You can propose a change and then write RFC on which people will vote. When it gets the majority of votes, you can implement the change in the language. 

GitHub issues are for reporting bugs. https://github.com/php/doc-en/issues is for bugs related to the manual on https://www.php.net/. The bug you have reported has been fixed, so this issue is closed. If you want to request changes to the language, you must go through the official process.

**Comment by cmb69** [comment]
To clarify, this has originally been reported at php-src, but I transfered it because it looked like a doc issue (and definitely is). And this is not so much about changing the language, but restoring the behavior prior to PHP 8.0.0. However, since PHP 8.0.0 has been released so long time ago, we cannot simply switch back, because that would break other code. Filing a feature request for php-src would also be mood, because nobody could decide for themselves to switch back, and would need to forward that to the internal mailing list for discussion (whether mailing lists are ancient technology or not, does not matter; it is the official discussion platform of php-src). So if you want to have the behavior changed, @WinterSilence, write to the mailing list. :)

> stop, stop.. not so fast.. what's about second part?

I'll have a look at this.

**Comment by WinterSilence** [comment]
@kamil-tekiela

> The bug you have reported has been fixed, so this issue is closed. 

I'm don't see any fixes

> Parameters of implemented methods have changed too.

BC

**Comment by cmb69** [comment]
Regarding DOMNamedNodeMap::item()'s parameter: this [was never optional](https://3v4l.org/DVPX0), but rather the arginfo was wrong. This is fixed as of PHP 8.0.0, but we usually do not document bugfixes in the PHP manual.

Sorry, if that breaks your code, but at least some breaks are to be expected in a major PHP version.

**Comment by WinterSilence** [comment]
@cmb69 > his was never optional, but rather the arginfo was wrong.

it's lie https://3v4l.org/TaTPB#v7.3.33

need complex update manual https://www.php.net/manual/ru/class.domnamednodemap still wrong

**Comment by WinterSilence** [comment]
@cmb69 that's changes break not only my code. I'm here, because it's break commerce framework with over 1k client's.

**Comment by WinterSilence** [comment]
@cmb69 reopen issue

**Comment by cmb69** [comment]
No, I will not reopen this ticket, because it has been closed with an associated commit. And that commit was not wrong; maybe it was incomplete, but that does not mean that it should be reverted. So, if you deem it necessary, file another ticket, and clearly state what should be documented. Better yet, provide a pull request.

>> his was never optional, but rather the arginfo was wrong.
>
> it's lie https://3v4l.org/TaTPB#v7.3.33

That is because the arginfo was wrong, like I said. The arginfo is used for reflection and for checking inheritance; however, actually calling a method has another mechanism to check the arguments (named zend_parse_parameters or ZPP for short). And the ZPP of DOMNamedNodeMap::item() required the argument (obviously, because which item should otherwise be retrieved?) We would not have fixed the arginfo in a minor version (or even a revision) for BC reasons, so this was postponed to a major version.

**Comment by WinterSilence** [comment]
@cmb69
That is because the arginfo was wrong, like I said. The arginfo is used for reflection and for checking inheritance; however, actually calling a method has another mechanism to check the arguments (named zend_parse_parameters or ZPP for short). 

you lie again and didn't even look at [code](https://3v4l.org/TaTPB#v7.3.33)! 

> Warning: Declaration of NamedNodeMap::item($index) should be compatible with DOMNamedNodeMap::item($index = NULL) in /in/TaTPB on line 9

**Comment by cmb69** [comment]
> you lie again and didn't even look at code!

I have looked at the code, and *tried* to explain; apparently, I failed, but I'm no longer interested in any conversation with you, since you called me a liar twice.

**Comment by kamil-tekiela** [comment]
Please be polite! Let me remind you again that we are volunteers who are trying to help you. You don't have to accuse us of lying. If you think there's a bug in PHP source code then please provide a pull request. 

FWIW I agree with cmb69. I don't see any bug in the code and what you are describing has been fixed in PHP 8.0

**Comment by nikic** [comment]
If you're looking for a signature that works with all PHP versions, this is it: https://3v4l.org/XSuNY

**Comment by WinterSilence** [comment]
@kamil-tekiela I call a spade a spade.  php7 - `<optional> $index`, php8 - `<required> int $index`  what's about LSP?
> Inheritance errors due to incompatible method signatures (LSP violations) will now always generate a fatal error. Previously a warning was generated in some cases. 
https://www.php.net/manual/en/migration80.incompatible.php
@nikic read all before give any answer
